import Head from 'next/head'
import {useState, useEffect} from 'react'
import { LightButton } from '../../components/light-button';
const hicdex ='https://api.hicdex.com/v1/graphql'

export const getStaticPaths = async() => {

  const queryObjkts = `
    query Objkts($tag: String!, $address: String!) {
     hic_et_nunc_token(where: {token_tags: {tag: {tag: {_eq: $tag}}}, creator: {address: {_eq: $address}}})  {
      id
       }
   }
   `;
   async function fetchGraphQL(queryObjkts, name, variables) {
    let result = await fetch(hicdex, {
      method: 'POST',
      body: JSON.stringify({
        query: queryObjkts,
        variables: variables,
        operationName: name,
      }),
    })
    return await result.json()
  }
    const { errors, data } = await fetchGraphQL(queryObjkts, 'Objkts', { tag: 'tarot', address: 'tz1X8tdMUnJZtMtQQdcfPbcEeLmfZZ7ybUpM' })
    if (errors) {
      console.error(errors)
    }

    const tarot = data.hic_et_nunc_token;
    const paths = tarot.map(item => {
      return {
        params: {
          tarotCard: `${item.id}`
        }
      }
    })

  return {
      paths,
      fallback: false,
  };
};

export const getStaticProps = async({params}) => {
  const queryObjktsbyId = `
      query ObjktsbyId($Id: bigint!) {
      hic_et_nunc_token(where: {id: {_eq: $Id}}) {
        artifact_uri
        description
        id
        title
        swaps {
          amount
          id
        }
      }
    }`
    async function fetchGraphQL(queryObjkts, name, variables) {
      let result = await fetch(hicdex, {
        method: 'POST',
        body: JSON.stringify({
          query: queryObjkts,
          variables: variables,
          operationName: name,
        }),
      })
      return await result.json()
    }

    const { errors, data } = await fetchGraphQL(queryObjktsbyId, 'ObjktsbyId', { Id: params.tarotCard})
    if (errors) {
      console.error(errors)
    }
    const card = data.hic_et_nunc_token
  console.log(card)

  return {
      props: {card},
  };
};
const TarotCard = ({card}) => { 
 console.log(card)

return(
  
    <>
      <Head>
        <title>Tezos Miami Next Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tezosmiami.ico" />
      </Head>
    <div className='cardcontainer'>
    {card[0].title}
        <img className='image' src={'https://cloudflare-ipfs.com/ipfs/' + card[0].artifact_uri.slice(7)}></img>
        {card[0].description}
    </div>
    <LightButton></LightButton>
</>
)

}
export default TarotCard;